name: gilbert-board
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - numpy
  - fastscapelib-f2py=2.8.1
  - notebook
  - ipykernel
  - matplotlib
  - ipywidgets
  - ipycanvas
  - voila
